/** 
 * Represents the tag applied to an agent's response (e.g., RECOMMENDATION, RISK, SKIP).
 * Now an open string type because tags are dynamically loaded from config.
 */
export type OutputTag = string;

export interface Meeting {
  id: string;
  title: string;
  status: 'setup' | 'active' | 'completed';
  created_at: string;
  participants: string[];          // agent IDs
  resourceFiles: string[];         // relative workspace file paths
  agenda: AgendaItem[];
  rounds: MeetingRound[];
  actionItems: ActionItem[];
  /** The first participant acts as discussion moderator. */
  moderatorId?: string;
  /** Per-agenda-item structured summaries generated by the moderator. */
  summaryRounds?: SummaryRound[];
  /** Auto-incremented OQ IDs created during this meeting. */
  openQuestionsCreated?: string[];
  /** Counter for open question IDs. */
  oqCounter?: number;
  /** Human decisions keyed by agendaItemId — required before agents can mark anything Accepted/Approved. */
  decisions?: Record<string, HumanDecision>;
  /**
   * Execution mode for this meeting.
   * "planning" (default): agents produce plans/recommendations only — no code changes allowed.
   * Future: "execution" mode may allow actual file writes via tool calls.
   */
  executionMode?: 'planning';
}

export interface AgendaItem {
  id: string;
  text: string;
  status: 'pending' | 'discussing' | 'resolved' | 'deferred';
  decision?: string;
  /** Set when a CLARIFICATION_FOR_HUMAN response is received — blocks further agent turns until human responds. */
  blockedByHuman?: boolean;
  /** Action gating policy for this item. Undefined = NORMAL (all tags allowed). */
  actionPolicy?: ActionPolicy;
}

export interface HumanDecision {
  option: string;
  decidedByHumanAt: string;
  notes?: string;
}

export type ActionPolicyMode = 'NORMAL' | 'BLOCK_ALL_ACTIONS' | 'ALLOW_ONLY';

export interface ActionPolicy {
  mode: ActionPolicyMode;
  /** Only for ALLOW_ONLY: whitelisted outputs by tag, optional agentId */
  allowed?: { tag: OutputTag; agentId?: string }[];
}

export interface MeetingRound {
  agendaItemId: string;
  agentId: string;
  response: string;
  timestamp: string;
  /** Parsed output tag from the response. */
  tag?: OutputTag;
  /** True when the agent responded with [SKIP]. */
  skipped?: boolean;
  /** True when this response was triggered by an INTERRUPT_REQUEST. */
  isInterrupt?: boolean;
  /** The agent ID that triggered this interrupt. */
  triggeredBy?: string;
  /** Interrupt requests parsed from this turn's response. */
  interruptRequests?: InterruptRequest[];
}

export interface InterruptRequest {
  mentionedAgentId: string;
  question: string;
  context?: string;
}

export interface SummaryRound {
  agendaItemId: string;
  /** Raw summary text (kept for backward compat + minutes). */
  summary: string;
  /** Structured fields parsed from moderator output. */
  problem?: string;
  options?: string[];
  recommendation?: string;
  risks?: string[];
  actions?: string[];
  openQuestionIds?: string[];
  decisionPrompt?: string;
  /** Machine-readable status emitted by the moderator for this round. */
  itemStatus?: 'open' | 'ready_for_human_decision' | 'blocked' | 'deferred' | 'resolved';
  deferReason?: string;
  blocker?: string;
  timestamp: string;
}

export interface ActionItem {
  id: string;
  text: string;
  assignedTo: string;              // agent ID
}
